physical_plan:
  graph:
    0: ''
    1: '0'
    2: '1'
    3: '2'
    4: '3'
    5: '4'
    6: '5'
    7: '6'
  pipes:
    0:
      name: MapperPipe_mel
      variant: INPROCESS
    1:
      name: MapperPipe_frequency_mask
      variant: INPROCESS
    2:
      name: MapperPipe_time_mask
      variant: INPROCESS
    3:
      name: MapperPipe__stretch
      variant: INPROCESS
    4:
      name: MapperPipe__spec
      variant: INPROCESS
    5:
      name: MapperPipe__resample
      variant: INPROCESS
    6:
      name: MapperPipe__read
      variant: INPROCESS
    7:
      name: LocalFSListerPipe
      variant: INPROCESS
  n_local_workers: 7