logical_plan:
  graph:
    0: ''
    1: '0'
    2: '1'
    3: '2'
    4: '3'
    5: '4'
    6: '5'
    7: '6'
    8: '7'
    9: '8'
  pipes:
    0:
      name: BatcherPipe(batch_size=8)
    1:
      name: MapperPipe_Normalize(mean=(0.1307,), std=(0.3081,))
    2:
      name: MapperPipe_GaussianBlur(kernel_size=(11, 11), sigma=(0.1, 2.0))
    3:
      name: MapperPipe_Grayscale(num_output_channels=1)
    4:
      name: MapperPipe_ColorJitter(brightness=None, contrast=None, saturation=None,
        hue=None)
    5:
      name: MapperPipe_RandomHorizontalFlip(p=0.5)
    6:
      name: MapperPipe_RandomResizedCrop(size=(244, 244), scale=(0.08, 1.0), ratio=(0.75,
        1.3333), interpolation=bilinear, antialias=warn)
    7:
      name: MapperPipe_to_float
    8:
      name: ImageReaderPipe
    9:
      name: LocalFSListerPipe
physical_plan:
  graph:
    0: ''
    1: '0'
    2: '7'
    3: '5'
    4: '2'
    5: '4'
    6: '3'
    7: '1'
    8: '6'
    9: '8'
  pipes:
    0:
      name: BatcherPipe(batch_size=8)
      variant: INPROCESS
    1:
      name: MapperPipe_Normalize(mean=(0.1307,), std=(0.3081,))
      variant: INPROCESS
    2:
      name: MapperPipe_GaussianBlur(kernel_size=(11, 11), sigma=(0.1, 2.0))
      variant: INPROCESS
    3:
      name: MapperPipe_Grayscale(num_output_channels=1)
      variant: INPROCESS
    4:
      name: MapperPipe_ColorJitter(brightness=(0.9, 1.1), contrast=(0.9, 1.1), saturation=(0.9,
        1.1), hue=(-0.1, 0.1))
      variant: INPROCESS 
    5:
      name: MapperPipe_RandomHorizontalFlip(p=0.5)
      variant: INPROCESS
    6:
      name: MapperPipe_RandomResizedCrop(size=(244, 244), scale=(0.08, 1.0), ratio=(0.75,
        1.3333), interpolation=bilinear, antialias=warn)
      variant: INPROCESS
    7:
      name: MapperPipe_to_float
      variant: INPROCESS
    8:
      name: ImageReaderPipe
      variant: INPROCESS
    9:
      name: LocalFSListerPipe
      variant: INPROCESS
  n_local_workers: 8