physical_plan:
  graph:
    3: ''
  pipes:
    0:
      name: MapperPipe__embedding
      variant: TF
    1:
      name: MapperPipe__truncate
      variant: TF
    2:
      name: MapperPipe__tokenize
      variant: TF
    3:
      name: TFLocalLinePipe
      variant: TF
      variant_ctx:
        num_parallel_calls: -1
      fused_pipes:
        - 2
        - 1
        - 0
