physical_plan:
  graph:
    0: '4'
    4: ''
    3: '0'
  n_local_workers: 1
  pipes:
    0:
      name: MapperPipe__embedding
      variant: TF
      variant_ctx:
        num_parallel_calls: -1
        variant_type: TF
    1:
      name: MapperPipe__truncate
      variant: INPROCESS
    2:
      name: MapperPipe__tokenize
      variant: INPROCESS
    3:
      name: TFLocalLinePipe
      variant: TF_RAY
      variant_ctx:
        max_inflight: 1500
        max_prefetch: 1500
        n_actors: 32
        num_parallel_calls: null
        submit_batch_size: 500
        use_threads: true
        variant_type: TF_RAY
      fused_pipes:
        - 2
        - 1
    4:
      name: PrefetcherPipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    # 5:
    #   fused_pipes:
    #   - 3
    #   - 2
    #   - 1
    #   name: FusedPipe
    #   variant: TF_RAY
    #   variant_ctx:
    #     max_inflight: 1500
    #     max_prefetch: 1500
    #     n_actors: 32
    #     num_parallel_calls: null
    #     submit_batch_size: 500
    #     use_threads: true
    #     variant_type: TF_RAY
